import 'package:calendar_view/calendar_view.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('WeekDaysHeader.hidden', () {
    test('returns a SizedBox.shrink for any input', () {
      final widget = WeekDaysHeader.hidden(const <DateTime>[]);
      expect(widget, isA<SizedBox>());
      expect((widget as SizedBox).width, 0.0);
      expect(widget.height, 0.0);

      final widget2 = WeekDaysHeader.hidden([
        DateTime(2026, 5, 11),
        DateTime(2026, 5, 12),
      ]);
      expect(widget2, isA<SizedBox>());
    });
  });

  group('WeekView.weekDaysHeaderBuilder', () {
    testWidgets('uses the custom builder when provided', (tester) async {
      List<DateTime>? receivedDates;

      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SizedBox(
              width: 600,
              height: 600,
              child: WeekView<Object?>(
                width: 600,
                controller: EventController<Object?>(),
                initialDay: DateTime(2026, 5, 13),
                minDay: DateTime(2026, 5, 11),
                maxDay: DateTime(2026, 5, 17),
                startHour: 8,
                endHour: 12,
                weekDaysHeaderBuilder: (dates) {
                  receivedDates = dates;
                  return const SizedBox(
                    key: ValueKey('custom-week-days-header'),
                    height: 24,
                    child: Center(child: Text('CUSTOM_WEEK_HEADER')),
                  );
                },
              ),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      expect(find.byKey(const ValueKey('custom-week-days-header')),
          findsOneWidget);
      expect(find.text('CUSTOM_WEEK_HEADER'), findsOneWidget);

      expect(receivedDates, isNotNull);
      expect(receivedDates!.length, 7);
      expect(receivedDates!.first, DateTime(2026, 5, 11));
      expect(receivedDates!.last, DateTime(2026, 5, 17));
    });

    testWidgets('WeekDaysHeader.hidden removes the default header content',
        (tester) async {
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SizedBox(
              width: 600,
              height: 600,
              child: WeekView<Object?>(
                width: 600,
                controller: EventController<Object?>(),
                initialDay: DateTime(2026, 5, 13),
                minDay: DateTime(2026, 5, 11),
                maxDay: DateTime(2026, 5, 17),
                startHour: 8,
                endHour: 12,
                weekDaysHeaderBuilder: WeekDaysHeader.hidden,
              ),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      // The day-number labels generated by the default _defaultWeekDayBuilder
      // must not be present anywhere on the page.
      for (final day in [11, 12, 13, 14, 15, 16, 17]) {
        expect(find.text('$day'), findsNothing,
            reason: 'Default day number $day should be hidden');
      }
    });

    testWidgets(
        'skips the Divider and full-day bottom border when builder is set',
        (tester) async {
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SizedBox(
              width: 600,
              height: 600,
              child: WeekView<Object?>(
                width: 600,
                controller: EventController<Object?>(),
                initialDay: DateTime(2026, 5, 13),
                minDay: DateTime(2026, 5, 11),
                maxDay: DateTime(2026, 5, 17),
                startHour: 8,
                endHour: 12,
                weekDaysHeaderBuilder: WeekDaysHeader.hidden,
              ),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      // No Divider widget should be in the header area when the consumer has
      // taken over via weekDaysHeaderBuilder.
      expect(find.byType(Divider), findsNothing);

      // The full-day events row's hardcoded 2px bottom border must also be
      // gone. We assert that no Container in the tree has a non-null
      // BoxDecoration whose border has a width of 2.
      final containersWithThickBottomBorder = find.byWidgetPredicate((widget) {
        if (widget is! Container) return false;
        final decoration = widget.decoration;
        if (decoration is! BoxDecoration) return false;
        final border = decoration.border;
        if (border is! Border) return false;
        return border.bottom.width == 2;
      });
      expect(containersWithThickBottomBorder, findsNothing);
    });

    testWidgets('default header still renders when builder is not provided',
        (tester) async {
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SizedBox(
              width: 600,
              height: 600,
              child: WeekView<Object?>(
                width: 600,
                controller: EventController<Object?>(),
                initialDay: DateTime(2026, 5, 13),
                minDay: DateTime(2026, 5, 11),
                maxDay: DateTime(2026, 5, 17),
                startHour: 8,
                endHour: 12,
              ),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      // The default _defaultWeekDayBuilder renders one cell per visible day,
      // each with a localized day number. We just verify at least one is on
      // screen to confirm the default path still works.
      final anyDayNumber = [11, 12, 13, 14, 15, 16, 17]
          .any((d) => find.text('$d').evaluate().isNotEmpty);
      expect(anyDayNumber, isTrue,
          reason: 'Default header should still render day numbers');
    });
  });

  group('MonthView.weekDaysHeaderBuilder', () {
    testWidgets('uses the custom builder when provided', (tester) async {
      List<DateTime>? receivedDates;

      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SizedBox(
              width: 420,
              height: 600,
              child: MonthView<Object?>(
                width: 420,
                controller: EventController<Object?>(),
                monthViewStyle: MonthViewStyle(
                  initialMonth: DateTime(2026, 5, 1),
                  minMonth: DateTime(2026, 5, 1),
                  maxMonth: DateTime(2026, 5, 31),
                ),
                monthViewBuilders: MonthViewBuilders<Object?>(
                  weekDaysHeaderBuilder: (dates) {
                    receivedDates = dates;
                    return const SizedBox(
                      key: ValueKey('custom-month-week-header'),
                      height: 16,
                      child: Center(child: Text('CUSTOM_MONTH_WEEK_HEADER')),
                    );
                  },
                ),
              ),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      expect(find.byKey(const ValueKey('custom-month-week-header')),
          findsOneWidget);
      expect(find.text('CUSTOM_MONTH_WEEK_HEADER'), findsOneWidget);

      expect(receivedDates, isNotNull);
      // 7 columns when weekends are visible (the default).
      expect(receivedDates!.length, 7);
    });

    testWidgets('WeekDaysHeader.hidden removes the weekday name row',
        (tester) async {
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SizedBox(
              width: 420,
              height: 600,
              child: MonthView<Object?>(
                width: 420,
                controller: EventController<Object?>(),
                monthViewStyle: MonthViewStyle(
                  initialMonth: DateTime(2026, 5, 1),
                  minMonth: DateTime(2026, 5, 1),
                  maxMonth: DateTime(2026, 5, 31),
                ),
                monthViewBuilders: MonthViewBuilders<Object?>(
                  weekDaysHeaderBuilder: WeekDaysHeader.hidden,
                ),
              ),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      // No WeekDayTile from the default builder should be in the tree once
      // the header is hidden.
      expect(find.byType(WeekDayTile), findsNothing);
    });

    testWidgets('default WeekDayTile still renders when builder is not set',
        (tester) async {
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SizedBox(
              width: 420,
              height: 600,
              child: MonthView<Object?>(
                width: 420,
                controller: EventController<Object?>(),
                monthViewStyle: MonthViewStyle(
                  initialMonth: DateTime(2026, 5, 1),
                  minMonth: DateTime(2026, 5, 1),
                  maxMonth: DateTime(2026, 5, 31),
                ),
              ),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      expect(find.byType(WeekDayTile), findsWidgets);
    });
  });

  group('MultiDayView.weekDaysHeaderBuilder', () {
    testWidgets('uses the custom builder when provided', (tester) async {
      List<DateTime>? receivedDates;

      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SizedBox(
              width: 600,
              height: 600,
              child: MultiDayView<Object?>(
                width: 600,
                controller: EventController<Object?>(),
                initialDay: DateTime(2026, 5, 13),
                minDay: DateTime(2026, 5, 11),
                maxDay: DateTime(2026, 5, 17),
                startHour: 8,
                endHour: 12,
                daysInView: 3,
                weekDaysHeaderBuilder: (dates) {
                  receivedDates = dates;
                  return const SizedBox(
                    key: ValueKey('custom-multi-day-header'),
                    height: 24,
                    child: Center(child: Text('CUSTOM_MULTI_DAY_HEADER')),
                  );
                },
              ),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      expect(find.byKey(const ValueKey('custom-multi-day-header')),
          findsOneWidget);
      expect(find.text('CUSTOM_MULTI_DAY_HEADER'), findsOneWidget);

      expect(receivedDates, isNotNull);
      expect(receivedDates!.length, 3);
    });
  });
}
